utils::globalVariables(c("include_detailed_annotation_info_helper","include_detailed_annotation_info_helper_custom","data",
                         "cell"       ,         "..col"       ,        "log2FC" ,             "marker"            ,  "EC_score_sum" ,       "EC_score_global"    , "Uberon_tissue"  ,     "uberon_onto"        ,
                         "Uberon_ID"   ,        "CL_celltype",         "CL_ID"   ,            "marker_type"      ,   "group"         ,      "EC_score"          ,  "marker_type_new",     "EC_score_new"       ,
                         "EC_score_scaled",     "specificity_scaled",  "specificity",         "combined_score"  ,    "score"          ,     "expr_scaled"      ,   "diff_score"      ,    "annotation_per_cell",
                         "ncell_tot_cluster",   "percentage"   ,       "seurat_clusters",     "weight"         ,     "cell_type"       ,    "..col_vec"       ,    "DO_ID"            ,   "NCIT_ID",
                         "cell_onto"         ,  "impact_score",        "color_combo"     ,    "EC_score_range",      "weight_range"     ,   "win_ct"         ,     "win_ct_border"     ,  "freq",
                         "condition"          , "node1.name",          "node2.name"       ,   "x",                   "y"                 ,  "NCIT_celltype" ,      "accordion_marker" ,
                         "ncell_celltype_cluster","perc_celltype_cluster","quantile_score_cluster","annotation_per_cluster","quantile_score_marker","quantile_diff_score",
                         "quantile_combined_score","perc_celltype_cluster","annotation_per_cluster",
                         "weight_scaled","dt_top_marker","EC_score_NCIT_global","DO_diseasetype","specificity_ratio","specificity_range","specificity_positive","specificity_negative",
                         "tot_cell_ct_cluster","disease_accordion_marker", "cell_onto","uberon_onto"))
